feat: improve git make-release version bump

diff --git a/git-make-release b/git-make-release
--- a/git-make-release
+++ b/git-make-release
@@ -5,6 +5,7 @@ RELEASE_BRANCH=0
 RELEASE_PATCH=0
 RELEASE_MINOR=0
 RELEASE_MAJOR=0
+BUMP_KIND=""
 
 # Parse options
 OPTS=$(getopt -o b,p,m,M --long release-branch,patch,minor,major -n 'parse-options' -- "$@")
@@ -13,9 +14,9 @@ eval set -- "$OPTS"
 while true; do
     case "$1" in
         -b | --release-branch ) RELEASE_BRANCH=1 ; shift ;;
-        -p | --patch ) RELEASE_PATCH=1 ; shift ;;
-        -m | --minor ) RELEASE_MINOR=1 ; shift ;;
-        -M | --major ) RELEASE_MAJOR=1 ; shift ;;
+    -p | --patch ) RELEASE_PATCH=1 ; BUMP_KIND="patch" ; shift ;;
+    -m | --minor ) RELEASE_MINOR=1 ; BUMP_KIND="minor" ; shift ;;
+    -M | --major ) RELEASE_MAJOR=1 ; BUMP_KIND="major" ; shift ;;
         -- ) shift; break ;;
         * ) break ;;
     esac
@@ -121,6 +122,16 @@ if [ "$NEXT_VERSION" == "$LAST_VERSION" ]; then
   exit 1
 fi
 
+# For requested automatic version bumps, confirm once before creating branch/MR/PR.
+if [ "${RELEASE_PATCH}" = "1" ] || [ "${RELEASE_MINOR}" = "1" ] || [ "${RELEASE_MAJOR}" = "1" ]; then
+  echo -n "Do you want to create and merge a ${BUMP_KIND} version bump to ${NEXT_VERSION} (y/N)? "
+  read -r ANSWER
+  if [ "${ANSWER,,}" != "y" ]; then
+    echo "Aborted."
+    exit 1
+  fi
+fi
+
 # write new version to CMakeLists.txt, if --patch, --minor or --major was given
 if [ "${RELEASE_PATCH}" = "1" ] || [ "${RELEASE_MINOR}" = "1" ] || [ "${RELEASE_MAJOR}" = "1" ]; then
   sed -i "${REPO_TOPLEVEL}"/CMakeLists.txt \
@@ -154,38 +165,13 @@ if [ "${RELEASE_PATCH}" = "1" ] || [ "${RELEASE_MINOR}" = "1" ] || [ "${RELEASE_
   git commit -m "chore: Bump version to ${NEXT_VERSION}"
   git push --set-upstream origin "${USER}/version-bump-${NEXT_VERSION}"
 
-  # check if repo is on github or gitlab, then create a PR/MR using the glab/gh CLI
-  origin=$(git remote get-url origin)
-  target_branch=$(git default-branch)
-  if [[ $origin = *gitlab* ]]; then
-    glab mr create --title "chore: Bump version to ${NEXT_VERSION}" --description "This MR bumps the version to ${NEXT_VERSION}" --target-branch "${target_branch}"
-  elif [[ $origin = *github* ]]; then
-    gh pr create --title "chore: Bump version to ${NEXT_VERSION}" --body "This PR bumps the version to ${NEXT_VERSION}" --base "${target_branch}"
-  else
-    echo "No gitlab or github remote found, please create a PR/MR manually."
-    exit
-  fi
-
-  # ask whether to merge the MR/PR and do so via the CLI
-  echo -n "Do you want to merge the PR/MR (y/N)? "
-  read -r ANSWER
-  if [ "${ANSWER,,}" != "y" ]; then
-    echo "Aborted."
-    exit 1
-  fi
-  if [[ $origin = *gitlab* ]]; then
-    glab mr merge -r -d
-  elif [[ $origin = *github* ]]; then
-    gh pr merge -r -d
-  else
-    echo "We should never end up here!"
-    exit 1
-  fi
+  # Reuse the generic helper for PR/MR creation + merge.
+  git push-with-pr -y --branch "${USER}/version-bump-${NEXT_VERSION}" --skip-pull
 
   # switch back to previous branch and delete the version bump branch
   git checkout "${CURRENT_BRANCH}"
   git pull
-  if [[ $origin = *gitlab* ]]; then
+  if [[ $(git remote get-url origin) = *gitlab* ]]; then
     git branch -d "${USER}/version-bump-${NEXT_VERSION}"
   fi
 fi
diff --git a/git-push-with-pr b/git-push-with-pr
--- a/git-push-with-pr
+++ b/git-push-with-pr
@@ -1,5 +1,34 @@
 #!/bin/bash -e
 
+AUTO_YES=0
+SKIP_PULL=0
+BR="${USER}/push-with-pr"
+
+while [[ $# -gt 0 ]]; do
+  case "$1" in
+    -y )
+      AUTO_YES=1
+      shift
+      ;;
+    -b | --branch )
+      if [ -z "$2" ]; then
+        echo "Missing argument for $1"
+        exit 1
+      fi
+      BR="$2"
+      shift 2
+      ;;
+    --skip-pull )
+      SKIP_PULL=1
+      shift
+      ;;
+    * )
+      echo "Usage: git push-with-pr [-y] [-b|--branch <branch>] [--skip-pull]"
+      exit 1
+      ;;
+  esac
+done
+
 TARGET_BRANCH=$( git default-branch )
 
 echo "Push the following commits to ${TARGET_BRANCH} via a scripted MR/PR:"
@@ -11,7 +40,6 @@ if [ "$N_COMMITS" -eq 0 ]; then
   exit 1
 fi
 
-BR="${USER}/push-with-pr"
 git push origin "HEAD:${BR}"
 
 # check if repo is on github or gitlab, then create a PR/MR using the glab/gh CLI
@@ -27,7 +55,7 @@ else
 fi
 
 # ask whether to merge the MR/PR
-if [ "$1" != "-y" ]; then
+if [ "${AUTO_YES}" != "1" ]; then
   echo -n "Do you want to merge the PR/MR without review (y/N)? "
   read -r ANSWER
   if [ "${ANSWER,,}" != "y" ]; then
@@ -47,4 +75,6 @@ else
 fi
 
 # pull the merged changes with rebase, so the changed commit ID in GitHub creates no problems
-git pull --rebase
+if [ "${SKIP_PULL}" != "1" ]; then
+  git pull --rebase
+fi
